# Database connection properties
spring:
  datasource:
    url: jdbc:mysql://192.168.200.88:3306/mungyeong_2?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: tsei1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate (JPA) properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG